### ISSUE TITLE
Feedback Markdown

### ISSUE THREAD

**Issue by francisvelueta** [CitlalliDMG/cdmx-2018-01-FE-markdown#16]
Buen proyecto implementando linea de comandos,tu feedback es: 

- Muy chido el ecmascript 7 en cuanto a las condiciones sin el if.

- Se pudiera aún acortar tmás tus lineas de código como en tus funciones checkPathToAbsolute, checkIfPathExist, readMarkdownFile, etc en donde sólo retornas inmediatamente.

- Muy bien tu solución del markdown, ya te faltaba poquito, ya que falta implementar promises o async

-Cómo buena práctica sería bueno mandar a llamar tu función de mdLinks en el cli.js con sus argumentos correspondientes.

- Muy buen readme, claro y conciso para instalar la librería ^^

Todo lo demás de manera particular está muy bien.

Felicidades por tu proyecto! :1st_place_medal:

**Comment by CitlalliDMG** [comment]
Muchas gracias por tu feedback Francias, intentaré implementar el async/await para la parte asíncrona y refactorizar el código para reducir líneas innecesarias 😊
