### ISSUE TITLE
Feedback markdown Q

### ISSUE THREAD

**Issue by alppacat** [CitlalliDMG/cdmx-2018-01-FE-markdown#17]
### Lo primero que resalta en tu proyecto es el README:
La documentación de tu proyecto está completa y no deja dudas en cuanto a la instalación o descripción de tu producto lo que creo que le da un plus (aún más).
### Ahora en cuanto a código:
No encuentro necesario comentar cada línea de tu código. Es más que suficiente tener nombres descriptivos. Como nos dijo el vato de Google (que no recuerdo su nombre), es mejor y más productivo tener los nombres de tus variables bastante descriptivos y reservar los comentarios para documentar el **Por Qué** -optaste por seguir ese camino, usar ese método etc-  y no el **Para Qué**.
La modularización de tu código mediante las funciones es genial y demuestra un gran avance en cuanto a la abstracción de los conceptos además de que se nota una clara intención de querer mantenerlas puras.

En general puedo decir que es uno de los proyectos más completos además de que no fue -tan- difícil poder comprender tu lógica, eso sí, lo único que hizo falta fue hacer uso de promesas, pero estoy segura que en tu próximo proyecto tendrás ese alcance! :D

**Comment by CitlalliDMG** [comment]
Mucha gracias Queletzú, mejoraré mi uso de los comentarios e intentaré hacer uso del async/await para las promesas que me faltaron en el siguiente alcance 😊
